kind: pipeline
name: Deploy

steps:
  - name: Notify - Start
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      username: Drone CI
      template: "🚀 [google-docs-clone] Build started: #{{ build.number }} ({{ build.branch }})"
    when:
      branch:
        - dev

  - name: Build & Push to ECR
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: ca-central-1
      registry: 322270498981.dkr.ecr.ca-central-1.amazonaws.com
      repo: cicd
      dockerfile: Dockerfile
      tags:
        - v${DRONE_BUILD_NUMBER}
        - latest
    when:
      branch:
        - dev

  - name: Deploy to EC2
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: aws_dev_host
      port:
        from_secret: aws_dev_port
      username: ubuntu
      ssh_key:
        from_secret: drone_ssh_key
      script:
        - echo "🧨 Deploying google-docs-clone (dev)..."
        - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 322270498981.dkr.ecr.ca-central-1.amazonaws.com
        - cd /opt/deploy/google-docs-clone
        - ./run.sh dev ${DRONE_BUILD_NUMBER}
    when:
      branch:
        - dev

  - name: Notify - Success
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      username: Drone CI
      template: >
        ✅ Build #{{ build.number }} (dev) succeeded!
        
        Commit: <{{ build.link }}|{{ truncate build.commit 8 }}>


    when:
      branch:
        - dev
      status:
        - success

  - name: Notify - Failure
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      username: Drone CI
      template: >
        ❌ Build #{{ build.number }} (dev) failed!
        
        Commit: <{{ build.link }}|{{ truncate build.commit 8 }}>


    when:
      branch:
        - dev
      status:
        - failure
