kind: pipeline
name: default

steps:
  - name: build
    image: node:18.18.0
    commands:
      - yarn install
      - yarn build

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: 3.96.197.221
      username: ubuntu
      key:
        from_secret: ssh_key
      port: 22
      strip_components: 0
      target: /home/ubuntu/app/jira-clone
      source:
        - .next/
        - public/
        - package.json
        - yarn.lock
        - next.config.js
        - node_modules/ # 需要包含 node_modules，或者在 EC2 上重新安裝

  - name: restart-app
    image: appleboy/drone-ssh
    settings:
      host: 3.96.197.221
      username: ubuntu
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /home/ubuntu/app/jira-clone
        - yarn install --production # 安裝生產依賴
        - pm2 delete jira-clone || true # 刪除舊的程序（如果存在）
        - pm2 start yarn --name "jira-clone" -- start --port 3001
        - sleep 5 # 等待應用啟動
        - sudo systemctl reload nginx
