kind: pipeline
name: Test

---
kind: pipeline
name: Deploy

steps:
  - name: 'notify - push'
    image: plugins/slack
    settings:
      room: general
      webhook:
        from_secret: slack_webhook
      username: Drone CI
      template: >
        Drone: <{{ build.link }}| Build #{{ build.number }} >

        Commit: <{{ build.link }}| {{ repo.name }} > / <http://drone.alphacore.cc/link/{{ repo.owner }}/{{ repo.name }}/tree/{{ build.ref }}|{{ build.branch }}> / <http://drone.alphacore.cc/link/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
  - name: 'notify - start build'
    image: plugins/slack
    settings:
      room: general
      webhook:
        from_secret: slack_webhook
      username: Drone CI
      template: Running...🏃🏃🏃
    when:
      branch:
        - dev
        - release

  - name: publish - build
    image: plugins/ecr
    environment:
      ENV: ${DRONE_SOURCE_BRANCH}
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_ACCESS_KEY:
        from_secret: aws_secret_access_key
    settings:
      build_args_from_env:
        - ENV
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo: st_twl_fe-${DRONE_SOURCE_BRANCH}
      registry: 381492122645.dkr.ecr.ap-northeast-1.amazonaws.com
      region: ap-northeast-1
      dockerfile: docker/Dockerfile
      tags:
        - v${DRONE_BUILD_NUMBER}
        - latest
    when:
      branch:
        - dev
        - release

  - name: 'deploy - AWS'
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: aws_${DRONE_SOURCE_BRANCH}_host
      port:
        from_secret: aws_${DRONE_SOURCE_BRANCH}_port
      username: droneci
      ssh_key:
        from_secret: drone_ssh_key
      script:
        - cd /opt/deploy/st-customer-fe
        - sudo sh run.sh ${DRONE_SOURCE_BRANCH} ${DRONE_BUILD_NUMBER}
        - date | sudo tee -a last_deploy_server_date.txt
    when:
      branch:
        - dev
        - release

  - name: 'notify dev finish'
    image: plugins/slack
    settings:
      room: general
      webhook:
        from_secret: slack_webhook
      username: Drone CI
      template: >
        Drone: <{{ build.link }}| Build #{{ build.number }} > {{#success build.status}} ✅ {{ else }} ❌ {{/success}}

        Url: <https://twl-dev.scarlet-tech.com>
    when:
      status:
        - success
        - failure
      branch:
        - dev

  - name: 'notify uat finish'
    image: plugins/slack
    settings:
      room: general
      webhook:
        from_secret: slack_webhook
      username: Drone CI
      template: >
        Drone: <{{ build.link }}| Build #{{ build.number }} > {{#success build.status}} ✅ {{ else }} ❌ {{/success}}

        Url: <https://twl.scarlet-tech.com>
    when:
      status:
        - success
        - failure
      branch:
        - release
