kind: pipeline
name: default

steps:
  - name: build
    image: node:18.18.0
    commands:
      - yarn
      - yarn build

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: 3.96.197.221
      username: ubuntu
      key:
        from_secret: ssh_key
      port: 22
      source: ./jira-clone # 傳送 build 出來的檔案
      target: /home/ubuntu/app # EC2 目標目錄

  - name: restart-server
    image: appleboy/drone-ssh
    settings:
      host: 3.96.197.221
      username: ubuntu
      key:
        from_secret: ssh_key
      port: 22
      script:
        - sudo systemctl restart nginx # 或者你的其他部署方式
