kind: pipeline
name: default

steps:
  - name: build
    image: node:18.18.0
    commands:
      - cd jira-clone
      - yarn install
      - yarn build

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: 3.96.197.221
      username: ubuntu
      key:
        from_secret: ssh_key
      port: 22
      strip_components: 0
      target: /home/ubuntu/app/jira-clone
      source:
        - jira-clone/.next/
        - jira-clone/public/
        - jira-clone/package.json
        - jira-clone/yarn.lock
        - jira-clone/next.config.js

  - name: restart-app
    image: appleboy/drone-ssh
    settings:
      host: 3.96.197.221
      username: ubuntu
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /home/ubuntu/app/jira-clone
        - yarn install --production
        - pm2 restart jira-clone || pm2 start yarn --name "jira-clone" -- start --port 3001
        - sudo systemctl reload nginx
