kind: pipeline
name: default

steps:
  - name: build
    image: node:18.18.0
    commands:
      - yarn install
      - yarn build

  - name: upload-files
    image: appleboy/drone-scp
    settings:
      host: 15.223.115.159
      username: ubuntu
      key:
        from_secret: ssh_key
      port: 22
      strip_components: 0
      target: /home/ubuntu/app/jira-clone
      source:
        - .next/
        - public/
        - package.json
        - yarn.lock
        - next.config.js
        - ecosystem.config.js
        - .env.production

  - name: restart-app
    image: appleboy/drone-ssh
    settings:
      host: 15.223.115.159
      username: ubuntu
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /home/ubuntu/app/jira-clone
        - yarn install --production
        - pm2 delete jira-clone || true
        - pm2 start ecosystem.config.js --env production
        - sudo systemctl reload nginx
